@host = http://localhost:5153

POST {{host}}/movies/publish
Accept: application/json
Content-Type: application/json

{
  "name": "Avengers",
  "description": "Lorem ipsum",
  "genre": "Heroes",
  "producer": "Marvel",
  "releaseDate": "2015-03-27"
}
###
