@host = http://localhost:5153

POST {{host}}/movies/publish
Accept: application/json
Content-Type: application/json

{
  "name": "Blancanieves",
  "description": "A bad movie!",
  "genre": "Adventure",
  "producer": "Dreams",
  "releaseDate": "2024-03-27"
}
###
