@host = http://localhost:5153

POST {{host}}/movies/publish
Accept: application/json
Content-Type: application/json

{
  "name": "Hangover 2",
  "description": "Friends doing crazy things",
  "genre": "Comedy",
  "producer": "Liongstage",
  "releaseDate": "2015-03-27"
}
###
