---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
      - name: reservation
        image: docker.io/catorres95/cinema-reservation:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: reservation-env
        - secretRef:
            name: reservation-secrets
      terminationGracePeriodSeconds: 180