---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
  labels:
    app: management
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: management
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
      - name: management
        image: docker.io/catorres95/cinema-management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: management-env
        - secretRef:
            name: management-secrets
      terminationGracePeriodSeconds: 180